language: java
sudo: false

addons: # get google-chrome-stable
  chrome: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
install: 
    - wget -N http://chromedriver.storage.googleapis.com/75.0.3770.90/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver
        
    #- sudo /sbin/modprobe tun
    #- sudo apt-get install openconnect
    #- sudo openconnect vpnac.inside-express.com/express_associate
    #- echo ALGO | sudo openconnect --no-xmlpost -v vpnac.inside-express.com/express_associate --no-cert-check -u JORGE --passwd-on-stdin
    #- echo ALGO | sudo openconnect -v vpnac.inside-express.com/express_associate -u JORGE --passwd-on-stdin
    #- echo ALGO | sudo openconnect -v -c express_cert.pem -k express_key.pem --cafile=express_cacert.pem vpnac.inside-express.com/express_associate -u JORGE --passwd-on-stdin -b
    #- sudo openconnect -v -c express_cert.pem -k express_key.pem --cafile=express_cacert.pem vpnac.inside-express.com/express_associate -b --os=win
    #- sudo openconnect -v -c express_cert.pem -k express_key.pem --cafile=express_cacert.pem vpnac.inside-express.com/express_associate -b
cache:
  directories:
  - "$HOME/.m2"

jobs:
  include:
  # 1.1 Semver check
  - stage: test
    jdk: oraclejdk8
    script: mvn verify -DforkCount=1 -Dtags="@Search" -Pcheck-semantic-version
#env: CHECK_SEMANTIC_VERSION=false
